### ISSUE TITLE
Flex on body causing undesirable side effects

### ISSUE THREAD

**Issue by danbull** [buildit/gravity-ui-web#133]
When `inline` patterns are immediate child of `body` in patternlab they are rendered as `block`. e.g. http://style.buildit.digital/?p=atoms-block-link

I propose maybe adding the `flex` CSS to a class rather than directly on the `body` element.

**Comment by james-nash** [comment]
My 2p: I'd like to avoid adding a class. The current approach not only gives you a sticky footer but more or less forces Gravity consumers to have a sensible structure:
```html
<body>
    <header>...</header>
    <main>...</main>
    <footer>...</footer>
</body>
```

Showing inline elements (or anything that would not normally sit alone on a page) in the pattern library is a bit of an edge case, and I don't think we should adjust the Gravity CSS itself to accommodate that.

That being said, it would of course be nice to fix up the presentation of those components in our pattern library. We can add some special rules into our `pattern-scaffolding.scss` to achieve this.

Right now, when PL shows a component by itself, it's placed directly into `<body>`. However, we can tweak the HTML top and tail that wraps around our pattern via `_meta/_00-head.mustache` and `_meta/_01-foot.mustache`. So, for instance we could add a `.sg-disable-sticky-footer` class to`<body>` and then use it to undo the flexbox behaviour. (We can control this per pattern too via `data.json`, so we could default to disabling the sticky footer, but then reverting to the normal Gravity behaviour for templates and pages.)


...but that's just my 2p 😜 

I'd be keen to hear from others too. @ThePeach ?

**Comment by danbull** [comment]
@james-nash sure, if we can make the assumption that nobody is ever going to need to add an inline element as the immediate child of the body then we could override it in the `pattern-scaffolding.scss` file. I considered that as well, it just felt unusual to have to do that.

`.sg-disable-sticky-footer` may sound a bit redundant if there is no footer on the pattern to disable.

I'd like to hear from @ThePeach too

**Comment by james-nash** [comment]
This should probably be worked on in conjunction with #148

**Comment by james-nash** [comment]
Ok, I was wrong. I'm coming around to not having the sticky footer be automatic, and instead introducing a class that switches on this behaviour. I.e. making it opt-in.

As it stands, this has various annoying side-effects:

* When Pattern Lab / Fractal's live dev server injects as `<script>` tag, it does so inside `<body>` and that sometimes screws with the layout
* For _very_ simple HTML pages, like our [CDN listing page](https://static.buildit.digital/gravity-ui-web/), it might make the page layout weird since it spaces out all the items on short pages.
* Because Pattern Lab doesn't always resize it's preview frame, you sometimes end up with a stupdily tall iframe. This rule then means you need to scroll down a mile to see the footer. While that _is_ ultimately PL's fault, it's nonetheless irritating.
* In light of issue #280, we can no longer assume that page header & footer will be direct descendents of the `body`.

So, yeah, let's remove this from our default styles and make it an object (or should it be utlility?) class. E.g.: `.grav-o-sticky-page-footer`.

You can then (optionally) apply that to whatever the immediate parent of page header, main and footer is.

**Comment by james-nash** [comment]
Closing this issue. PR #339 provides a way of opting out of the default sticky footer on `<body>` as well as disabling the default sticky footer completely in custom SASS builds.
