### ISSUE TITLE
Travis doesn't run commit lint

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-web#210]
**Describe the bug**
We currently only have `commitlint` configured to run as one our pre-commit hooks.

However, sometimes incorrectly formatted commit messages can still creep in - e.g. when someone has not (recently) run `npm install` and therefore doesn't have that hook setup.

To spot such erroneous commit messages sooner, we should therefore also run `commitlint` in Travis, so that PR checks fail if any of the commits messages don't follow the correct format.

It _looks_ like this was already setup at some point, but the relevant line in `.travis.yml` has been commented out: https://github.com/buildit/gravity-ui-web/blob/develop/.travis.yml#L12

@ashblue Any idea why that might be? Was it intentionally disabled?

**Comment by ashblue** [comment]
Had to disable it to get the first commit to merge in properly (old commits missing the proper syntax). For some weird reason trying to rewrite the commit messages was pretty risky since there were open PRs. I'll put up a PR to see if it's working again since everything committed since the last version should have the proper syntax.

**Comment by james-nash** [comment]
Awesome. Thanks!
