### ISSUE TITLE
Unable to use `body >` styles when consuming in SPA

### ISSUE THREAD

**Issue by danbull** [buildit/gravity-ui-web#280]
**Is your feature request related to a problem? Please describe.**
When using Next.js things like `Header` are not the immediate child of `body` because extra `div`s wrapping divs are rendered. This would also be the case for any React app and possibly other frameworks.

**Describe the solution you'd like**
`body >` selectors need to a refactored to less specific to the DOM

**Describe alternatives you've considered**
n/a

**Additional context**
I noticed this when using the Toggle Menu component which requires the DOM to be in this structure `body>header .grav-c-toggle-menu`. I suspect there may be other examples.

**Comment by james-nash** [comment]
Fair enough. I think we can have classes for page header and footer. I'm coming around the idea that there are valid reasons why they might not be _direct_ descendents of `body` in all cases.

As it turns out, as long as the top level `<header>` and `<footer>` are not wrapped in other HTML5 sectioning elements, assistive tech will consider them as the page's header & footer and automatically assign them the relevant ARIA landmakr roles:

>Assistive technologies can identify the main header element of a page as the banner if is a descendant of the body element, and not nested within an article, aside, main, nav or section subsection.
>
>_source: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role_

I, mistakenly as it turns out, had previously thought they had to be _direct_ children of body and our CSS selectors were intended to enforce that mark-up best practise.

Since that's not the case, I'm happy to move to class-based selectors (`.grav-c-page-header` and `.grav-c-page-footer`) that would then let you nest the page header and footer within other containers.

What we can do though is still support the element-based selectors too. That maintains backwards compatibility for the website and GMS (Gravity Metalsmith Seed) and could be useful for other simple projects:

```scss
.grav-c-page-header,
body > header {
    // ...
}
```

The only thing to keep an eye on is what effect that has on the CSS filesize. It'll add a little but of bloat, but in this instance I think it'll be negligible.

**Comment by james-nash** [comment]
On a related note - while I'm happy to move to classes here - I am curious: _Why_ does NEXT insist on adding wrapper DIVs? And, is that something that can be disabled?

I mean, from a semantic purity point of view, it seems benign in this case. But, I do find it concerning that it would impose any restrictions on our choice of mark-up at all.

**Comment by danbull** [comment]
Unfortunately it's not just Next, it's highly likely any SPA. Also on this topic, some React modules (e.g. the drag 'n' drop library I'm using) also render extra wrapping `div`s. I've not encountered problems with any other Gravity selectors yet but I'd say immediate child selectors may have to be reserved for cases where we can guarantee the structure e.g. `ul > li`

**Comment by dw-buildit** [comment]
We might be able to still be opinionated about the `body > [header, main, footer]` structure. At least in React you might be able to use fragments to render the contents without adding wrapping divs. This won't help for react libraries we don't control of course - so we do still need to be conscious of issues with being over opinionated. Also, i'm not certain of Fragment limitations so it might not work 🤔
